services:
  postgres:
    image: postgres:14
    container_name: phone-shop-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jihed
      POSTGRES_DB: catalogue_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    container_name: phone-shop-mongo-1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  catalogue:
    build:
      context: ./services/catalogue
    container_name: phone-shop-catalogue-1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: jihed
      DB_NAME: catalogue_db
    expose:
      - "8002"
    ports:
      - "8002:8002"

  order:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    container_name: phone-shop-order-1
    restart: always
    depends_on:
      mongo:
        condition: service_started
    env_file:
      - ./services/order/.env
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./services/order:/app
      - ./shared-utils:/app/shared-utils

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    container_name: phone-shop-auth-1
    restart: always
    depends_on:
      mongo:
        condition: service_started
    env_file:
      - ./services/auth/.env
    expose:
      - "5000"
    ports:
      - "5000:5000"

  nginx:
    image: nginx:alpine
    container_name: phone-shop-nginx-1
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - catalogue
      - order
      - auth

volumes:
  postgres_data:
  mongo_data:
