# Use a Go image that supports go 1.24.2
FROM golang:1.24.2-alpine

WORKDIR /app

# Copy go.mod and go.sum for dependency caching
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application
COPY . .

# Build the Go application
RUN go build -o catalogue main.go

# Expose the port the app listens on
EXPOSE 8080

# Run the application
CMD ["./catalogue"]
